declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_APP_NAME?: string;
    EXPO_PUBLIC_APP_SCHEME?: string;
    EXPO_PUBLIC_APP_BASE_URL?: string;
    EXPO_PUBLIC_PRIVACY_POLICY_URL?: string;
    EXPO_PUBLIC_FIREBASE_API_KEY?: string;
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
    EXPO_PUBLIC_FIREBASE_PROJECT_ID?: string;
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET?: string;
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string;
    EXPO_PUBLIC_FIREBASE_APP_ID?: string;
    EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID?: string;
    EXPO_PUBLIC_EAS_PROJECT_ID?: string;
    EXPO_PUBLIC_REVENUECAT_API_KEY_IOS?: string;
    EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID?: string;
    EXPO_PUBLIC_MERCADO_PAGO_PUBLIC_KEY?: string;
    EXPO_PUBLIC_DEFAULT_TRIAL_DAYS?: string;
  }
}
